version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
      - run:
          name: Ejecutar tests
          command: |
            python -m unittest discover tests

workflows:
  version: 2
  test:
    jobs:
      - test 